import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import bg from "../img/bg.jpg";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Yorunaka",
  description: "Generated by Vincent Louis F",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="webicon" href="../img/webicon.png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: `url(${bg.src})`,
        }}>
        {children}
      </body>
    </html>
  );
}
